#1189 R3010B_CashOnHand of CP/CR/BP/BR
IRPTeam/IRP pull request #1190
Opened 2021-11-17 17:43 UTC by DitriXNew

fixed  #1189

2021-11-17 17:51 UTC, bryaleks requested changes

2021-11-17 17:51 UTC, bryaleks commented on IRP/src/Documents/CashReceipt/ManagerModule.bsl
> -		   |	OR PaymentList.IsCashTransferOrder
@DitriXNew Обращаю ваше внимание на невнимательность

2021-11-17 17:54 UTC, bryaleks requested changes

2021-11-17 17:54 UTC, bryaleks commented on IRP/src/Documents/CashReceipt/ManagerModule.bsl
> +		   |	TRUE1 ";
@DitriXNew Here the hand slipped apparently...

2021-11-17 17:58 UTC, bryaleks requested changes

2021-11-17 17:58 UTC, bryaleks commented on IRP/src/Documents/CashReceipt/ManagerModule.bsl
> +		   |	TRUE1 ";
@DitriXNew тут опечатка

2021-11-18 11:37 UTC, merged

2021-11-30 11:04 UTC, DitriXNew commented on IRP/src/Documents/BankPayment/ManagerModule.bsl
> +		   |	TRUE";
123123123

2021-11-30 11:05 UTC, DitriXNew commented on IRP/src/Documents/CashReceipt/ManagerModule.bsl
> +		   |	TRUE1 ";
123123123

2021-11-30 11:06 UTC, DitriXNew commented on IRP/src/Documents/BankPayment/ManagerModule.bsl
> +		   |	TRUE";
Не ту фкнкцию