Rename Accum register R3050T_RetailCash to R3050T_PosCashBalances
IRPTeam/IRP pull request #1336
Opened 2022-05-17 21:08 UTC by klyaksa

#1327

2022-05-17 22:17 UTC, DitriXNew requested changes
Также стоит исправить сразу синонимы и наименование в тестах

2022-05-17 22:17 UTC, DitriXNew commented on IRP/src/CommonModules/DocCashStatementServer/Module.bsl
>  	|	R3050T_RetailCash.CommissionTurnover AS Commission,
Не переименовано

2022-05-17 22:17 UTC, DitriXNew commented on IRP/src/AccumulationRegisters/R3050T_PosCashBalances/R3050T_PosCashBalances.mdo
>      <value>R3050 Retail cash</value>
Не переименованы синонимы

2022-05-18 02:52 UTC, klyaksa commented
Добавила переименование синонимов в тексте

2022-05-19 18:14 UTC, klyaksa commented on IRP/src/CommonModules/DocCashStatementServer/Module.bsl
>  	|	R3050T_RetailCash.CommissionTurnover AS Commission,
Уже переименовано

2022-05-20 09:42 UTC, DitriXNew requested changes
IRP\features\Internal\_0287 Services\_0287Services.feature
И в тестах надо переименовать R3050 Retail cash

2022-05-20 09:42 UTC, DitriXNew commented on IRP/src/AccumulationRegisters/R3050T_PosCashBalances/R3050T_PosCashBalances.mdo
>      <value>R3050 Retail cash</value>
Не переименовали

2022-05-20 17:19 UTC, klyaksa commented on features/Internal/_0287 Services/_0287Services.feature
> +		And I select "R3050 Pos cash balances" exact value from "Register" drop-down list
Теперь вроде бы всё :)

2022-05-22 16:22 UTC, DitriXNew commented
Увы, один тест упал, где-то еще осталось :)
https://dev.irpteam.com/tc/repository/download/Build_30_RunVA/37422:id/allure-report.zip!/index.html#categories/6ec29e992aa5f5c91a94432860ef9291/97634091e92f9278/

При логине нажмите что вы гость.

2022-05-22 16:29 UTC, DitriXNew commented
Подсказка - я вам уже писал выше, что надо сделать.

2022-05-22 22:28 UTC, DitriXNew approved these changes

2022-05-22 22:28 UTC, merged

2022-05-23 02:24 UTC, klyaksa commented
Я с тестами не работала, было очень интересно. Спасибо :)