price by unit
IRPTeam/IRP pull request #1453
Opened 2022-08-08 20:09 UTC by andreyvorobyov2

price by unit

2022-08-09 14:27 UTC, DitriXNew requested changes

2022-08-09 14:27 UTC, DitriXNew commented on IRP/src/CommonModules/GetItemInfo/Module.bsl
> -		Result = New Structure();
почему не в фнкиции конструктора?

2022-08-09 14:45 UTC, andreyvorobyov2 commented on IRP/src/CommonModules/GetItemInfo/Module.bsl
> -		Result = New Structure();
хз что такое функция конструктора, но эта строчка красного цвета)

2022-08-10 10:50 UTC, DitriXNew commented on IRP/src/CommonModules/GetItemInfo/Module.bsl
> -		Result = New Structure();
Ну раз красное, значит быстрее. Все ок

2022-08-11 12:13 UTC, merged