Editor for Additional Attributes
IRPTeam/IRP pull request #1619
Opened 2022-12-15 21:09 UTC by DementorAK

2022-12-16 11:03 UTC, DitriXNew requested changes

2022-12-16 11:03 UTC, DitriXNew commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +				ErrorDescription = ErrorDescription();
зачем?

2022-12-16 11:03 UTC, DitriXNew commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +		Query.Text = "SELECT T." + TypeOption_FieldRef.Name + " AS Ref FROM " + Path + " AS T";
почемуц не Схему запросов использовть?

2022-12-16 11:03 UTC, DitriXNew commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +		Query.Text = StrTemplate(
вынеси текст запроса за шаблон

2022-12-16 11:03 UTC, DitriXNew commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +			AvailableItems_Table.Add()["Property"] = AvailableItem;
почему не через точку?

2022-12-16 11:03 UTC, DitriXNew commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +		Query.Text = StrTemplate(
вынеси за шаблон запрс

2022-12-16 11:03 UTC, DitriXNew commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +	Try
а это зачем? Try вообще не надо использовать, можно без него сделать?

2022-12-20 13:05 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +	RefsList = Parameters["RefsList"]; // Array, Undefined
А меня есть параметр формы, но поскольку тип Массив не поддерживается, то сделал его типа Произвольный. А для произвольных типов, если их куда-то присваивать при строгой типизации, то выдает ошибку: "Feature access "RefsList" has no return type".

Этот функционал заполнения был для открытия из команды с передачей ее параметра. Поскольку команды больше нет, то переделал на использование Списка Значений, который разрешен в параметрах формы. В команде расширения IM тоже исправил массив на список.

2022-12-20 13:05 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +		TypeKey = TypeOf(RefsList[0]);
этот код уже переделан

2022-12-20 13:05 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +//  Field - FormField - Field
Какой именно?

2022-12-20 13:08 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +Procedure CheckRowModified(Form, RowValue)
Он не может быть Undefined - единственная функция, где я получал второй параметр из формы - это PropertiesTableValueOnChange, которая вызывалась при редактировании ячеек существующей строки. Но проверку на всякий случай добавил.

2022-12-20 13:13 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +	CheckRowModified(ThisObject, RowValue);
Добавил

2022-12-20 13:14 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +//	** Value - Structure:
Нет, имелось в ввиду именно Соответствие.

2022-12-20 13:15 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +	OT_String = "ObjectTable";
Из-за строгой типизации. Если обращаться к свойству по литералу, а не по переменной, то делает варнинг. Если через точку, то вообще красная ошибка.

2022-12-20 13:22 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +	"SELECT
Переделал на шаблон, но при чем тут редактор запросов? Он все равно не сможет открыть:
![image](https://user-images.githubusercontent.com/5967038/208677199-8f8d788b-9d86-4add-8bf3-5c51fc70c19f.png)

2022-12-20 13:24 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +	//@skip-warning
???

2022-12-20 13:24 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +//  NewFormItem - FormFieldExtensionForATextDocument, FormFieldExtensionForAGanttChartField, FormFieldExtensionForALabelField, FormFieldExtensionForADendrogramField, FormFieldExtensionForAPictureFiel
Комментарий сгенерировало ЕДТ

2022-12-20 13:26 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +Procedure CreateConditionalAppearance(Form, NewFormItem, isCollection)
НЕ понял вопрос

2022-12-20 13:26 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +		ItemPreffics = "";
Где?

2022-12-20 13:28 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +				ErrorDescription = ErrorDescription();
Согласен. Нужно переписать на проверку метаданных и тогда Попытка Исключение уже не нужны

2022-12-20 13:28 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +		Query.Text = "SELECT T." + TypeOption_FieldRef.Name + " AS Ref FROM " + Path + " AS T";
У нас есть функции общих модулей для верстки запросов?

2022-12-20 13:31 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +		Query.Text = StrTemplate(
Не понял. Шаблон генерирует текст запроса.

2022-12-20 13:33 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +			AvailableItems_Table.Add()["Property"] = AvailableItem;
Потому что строгая типизация:
![image](https://user-images.githubusercontent.com/5967038/208679080-1df23c3b-fe9e-4721-be26-e0d0c1d23090.png)

2022-12-21 08:35 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +		Query.Text = StrTemplate(
Видимо продолжение предыдущего комментария. Запрос отдельно, а в условии два варианта текста запроса, которые верстаются шаблоном. Не понял что нужно

2022-12-21 08:57 UTC, DementorAK commented on IRP/src/DataProcessors/ObjectPropertyEditor/Forms/Form/Module.bsl
> +	Try
Эта функция обвертка над получением значения исключительно для подавления ошибки ЕДТ:
![image](https://user-images.githubusercontent.com/5967038/208862926-c32adf0a-c1af-4e7a-9aa2-3c0d92e01a35.png)

2022-12-21 09:59 UTC, merged