#2424 New data processor EditDocumentsMovements
IRPTeam/IRP pull request #2434
Opened 2024-04-02 16:10 UTC by mybracho

2024-04-03 06:00 UTC, DitriXNew requested changes

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/CommonFunctionsServer/Module.bsl
> +	Structure.Insert("OnChangeProcedureName","");
Функции конструкты должны инициализировать значение того типа, который указан. Надо сделать инициализацию значениями по умолчанию.

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/CommonFunctionsServer/Module.bsl
> +	ParentName 			= CreactionStructure.ParentName;
Не надо делать выравнивание отступами, а то в зависимотси от шрифта - оно потом начинает плыть

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/CommonFunctionsServer/Module.bsl
> +//  CreactionStructure - see BlankFormTableCreationStructure
See - с большой буквы

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("Error_144", NStr("en = 'Document''s movements were changed manually. Posting is denied'", Lang));
надо использовать симаол `, а не '

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("Error_144", NStr("en = 'Document''s movements were changed manually. Posting is denied'", Lang));
Document`s movements have been modified manually. Reposting or undoposting is disabled due to manual adjustments.

Может так лучше?

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("Error_145", NStr("en = 'There are differences between current movements and potential movements in register [%1]'", Lang));
Differences detected between the current manual movements and the potential automated movements in register [%1].

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("InfoMessage_036", NStr("en = 'New document movements are no different from manual corrections. The ""Manual movements edit"" checkbox can be removed'", Lang));
"New document movements are identical to the manual corrections. The "Manual Movements Edit" checkbox is now unnecessary and can be removed."

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("QuestionToUser_029", NStr("en = 'New document movements are no different from manual corrections. The ""Manual movements edit"" checkbox can be removed. Remove check-box?'", Lang));
"New document movements match the manual corrections, making the "Manual Movements Edit" checkbox unnecessary. Would you like to remove this checkbox?"

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/LockDataModificationPrivileged/Module.bsl
> +	CheckManualMovementsEdit(Source, Cancel, Source.IsNew());
Ну это прям не удачно ты придумал. Функция отвечает за одно. А ты прям нагло туда засунул другую ответственность.
Тогда уже переименую подписки, назови ее как то по ее ответственности и там уже выстраивай цепочки.

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/LockDataModificationPrivileged/Module.bsl
> +Function CheckManualMovementsEdit(Source, Cancel, IsNew)
Что это за функция такая?

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/PostingServer/Module.bsl
> +	If Parameters.Cancel Then
А ты проверил обработку фикса движений документов? Она же тоже выпадет в ошибку в таком случае и не покажет ничего.

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/PostingServer/Module.bsl
> +
пустую строку убери

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/PostingServer/Module.bsl
> +// * Messages - Array -
Array чего?
Array Of String

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/PostingServer/Module.bsl
>  // ** Key - MetadataObject -
MetadataObject  - Просто так? Может там должна быть метадата документов?

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/PostingServer/Module.bsl
> +	ManualRecordsDifference = False;
ManualRecordsDifference - название не говорит ни о чем.
Или переименуй в ManualRecordsHasDifference, но лучше isManualRecordsHasDifference, вот так с маленькой буквы.

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/CommonModules/PostingServer/Module.bsl
> +			If Parameters.ManualMovementsEdit Then;
Ну тут даже сонар прифигел от ; и как оно скомпилилось то?

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +	If Parameters.Property("DocRef") Then
нет, так мы не делаем.
Идешь в форму, в параметры, там создаешь параметр DocRef, с нужным типом, который всегда будет проинициализирован хначением по умолчаю, и там уже сравнивает, что если Parameters.DocRef.isEmpty(), ну или = Undefined, тогда ла ла ла. Никаких проверок на наличие в структуре параметров ключей.

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +		Object.DocumentRef = Parameters.DocRef;
А если документ будет помечен на уделание?

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +	ClearAttributes();
если документ пустой, может все же вызывать очистку данных? Ну т.е. она не должна зависить от того - пустой или нет док.

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +	DocumentObject = Object.DocumentRef.GetObject();
Не не не, я же говорил - смотри как обработка фикса документов работает.
Никаких получений объектов.
```bsl
Procedure PostingInfo_UpdateTable(Ref, NewMovementStorage)
	Query = New Query("SELECT * FROM " + CurrentRegName + " WHERE Recorder = &Ref");
	Query.SetParameter("Ref", Ref);
	CurrentMovement.Load(Query.Execute().Unload());
	NewMovement.Load(NewMovementStorage.Get());
EndProcedure
```

Вот такая там есть аккуратная функция. Можешь ее вынести в общий модуль постинга и задействовать ее.

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +	CurrentMovementStructure.Form					= ThisForm;
ThisObject

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +	If GetAttributesFromRef(Object.DocumentRef, "ManualMovementsEdit").ManualMovementsEdit Then
1. Зачем перекидывать функцию `GetAttributesFromRef` на сервер? этот модель доступен с клиента.
2. Тебе надо не эта функция, а вот эта - `GetRefAttribute`, если тебе надо получить только один реквизит

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +		ShowQueryBox(QuestionToUserNotify, R().QuestionToUser_030, QuestionDialogMode.YesNo);
Та зачем оно тебе надо? Делай через Асинх, зачем эти спагети?

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +EndFunction
не нужна

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +	Items.FormWriteMovements.Enabled	= ManualMovementsEdit;
Убери выравнивание

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +	Items.FormWriteMovements.Enabled	= ManualMovementsEdit;
Ты или функцию назови по типу SevVesible, или уже следуй принципам DI - и передавай туда параметром `ManualMovementsEdit`, что бы было явным вызовом, типо вот я туда передаю параметр и вот от него что то зависит, а то сейчас смотришь код - функция вроде определена явно, а внутри - неявные зависимости. Для 1с это норма, но лучше стараться делать явные зависимости

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +	Posted = CommonFunctionsServer.GetAttributesFromRef(Object.DocumentRef, "Posted").Posted;
дрйга функция

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +		TextMessage = R().Error_146;
ты б уже или переменную назвал по содержанию, или ключ. А то вроде код полезный - а что в нем...

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +Procedure RereadData(Command)
Reread что? RereadPostingData?

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +				RegisterRecords.DataExchange.Load = True;
Тут наверное надо будет еще подумать, так как есть блокировки регситров, и их игнорировать не надо. Так что лучше сделать отдельную галочку - типо непосредственное изменение.

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +				RegisterRecords.Read();
Зачем читать чтобы потом очистить? Просто лишняя нагрузка на базу

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +	Array = New Array;
Тип не указал

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +&AtServer
Не вижу включенной строгой типизации

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +
Где то я уже видел этот код выше, может его тоже сюда затянуть?

2024-04-03 06:00 UTC, DitriXNew commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +			If ArrayItemStructure.Ref = Object.DocumentRef Then
If `Not` ArrayItemStructure.Ref = Object.DocumentRef Then
    Continue

Умень когнитивную сложность

2024-04-03 09:41 UTC, mybracho commented on IRP/src/CommonModules/LockDataModificationPrivileged/Module.bsl
> +Function CheckManualMovementsEdit(Source, Cancel, IsNew)
Удалил

2024-04-03 09:46 UTC, mybracho commented on IRP/src/CommonModules/PostingServer/Module.bsl
> +	If Parameters.Cancel Then
Проверил. Обработка при наличии ручных изменений показывает, что есть расхождения по регистрам.

![image](https://github.com/IRPTeam/IRP/assets/163126906/7ff0f658-d9fc-493d-89b0-ec0264a2f8bc)

2024-04-03 09:56 UTC, mybracho commented on IRP/src/DataProcessors/EditDocumentsMovements/Forms/Form/Module.bsl
> +		Object.DocumentRef = Parameters.DocRef;
Далее есть проверка, что только у проведенного документа могут быть изменены движения.

2024-04-04 07:32 UTC, DitriXNew commented on IRP/src/CommonModules/CommonFunctionsServer/Module.bsl
> +	Structure.Insert("Form");
Пропиши тут явно Undefined

2024-04-30 19:54 UTC, merged