#2459 ExpenseAccruals
IRPTeam/IRP pull request #2461
Opened 2024-04-24 12:22 UTC by mybracho

2024-04-26 14:20 UTC, DitriXNew requested changes

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("EmptyTransactionType", NStr("en = 'Transaction type not entered'", Lang));
Лучше префикс оставлять, типо Error_, Info_, или префикс по объекту, так же регион посмотри.

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/DefinedTypes/typeAddPropertyOwners/typeAddPropertyOwners.mdo
> +    <types>DocumentRef.ExpenseAccruals</types>
а второй где?

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/AdditionalCostAllocation/ManagerModule.bsl
> +		   |	value(enum.OtherPeriodExpenseType.ItemsCost) as OtherPeriodExpenseType
Если стоит звездочка, то свои поля надо описывать ДО нее, иначе может быть ошибка, что поле уже существует. Та и в целом мы от звездочек отказываемся, так что можешь тоже тут отказаться от нее

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/ExpenseAccruals/Forms/PickupExpenseForm/Module.bsl
> +	|	R6070T_OtherPeriodsExpenses.Basis AS Document,
Вынеси это в функцию, зачем миллион строк нужен в процедуре создания?

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/ExpenseAccruals/Forms/PickupExpenseForm/Module.bsl
> +	CurrentData = ExpenseValueTable.FindByID(RowID);
надо в заголовке функции тип указывать, а не внутри переопределять

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +//  Parameters - Structure:
ссылку надо на внешнюю функцию

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +//  AddInfo - Undefined - Add info
Что это за конструкция такая?

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +EndProcedure
В этом свободном месте озеро будет? :)

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +// * QueryTextsSecondaryTables - Array -
Аррай чего?

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +EndProcedure
Табцляция

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +EndProcedure
Лишние параметры описаны

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +EndProcedure
лишние параметры

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +EndFunction
Табуляции и там точно надо прям столько заглушек ставить?

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/RevenueAccruals/Forms/PickupRevenueForm/Module.bsl
> +	|	R6080T_OtherPeriodsRevenues.Basis AS Document,
Вынеси в функцию

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/RevenueAccruals/Forms/PickupRevenueForm/Module.bsl
> +	RowID = RowSelected; // Number
.

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/RevenueAccruals/ManagerModule.bsl
> +//  Parameters - Structure:
.

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/RevenueAccruals/ManagerModule.bsl
> +// Parameters: see PostingGetDocumentDataTables
.

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/RevenueAccruals/ManagerModule.bsl
> +	QueryArray.Add(R5021T_Revenues());
Отсортируй

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/Documents/RevenueAccruals/ManagerModule.bsl
> +//  PostingMode - DocumentPostingMode
.

2024-04-26 14:20 UTC, DitriXNew commented on IRP/src/InformationRegisters/AttachedFilesControl/AttachedFilesControl.mdo
> -  <useStandardCommands>true</useStandardCommands>
Разве это относится к этой задаче?

2024-04-26 14:32 UTC, mybracho commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +//  Parameters - Structure:
Тут не понял. На какую внешнюю функцию, если это и есть внешняя функция? Или надо сделать функцию конструктор такой структуры в модуле Posting?

2024-04-26 14:35 UTC, mybracho commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +EndProcedure
Тут не понял. Описывать разве не все параметры надо?

2024-04-26 14:36 UTC, mybracho commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +EndFunction
Про табуляции согласен, а с общими реквизитами не работает нормально EDT получается.

2024-04-26 14:37 UTC, mybracho commented on IRP/src/InformationRegisters/AttachedFilesControl/AttachedFilesControl.mdo
> -  <useStandardCommands>true</useStandardCommands>
к этой нет. Лёша в чате Текли сделал замечание про это. Я решил здесь заодно исправить.

2024-04-26 15:10 UTC, bryaleks commented on IRP/src/InformationRegisters/AttachedFilesControl/AttachedFilesControl.mdo
> -  <useStandardCommands>true</useStandardCommands>
Это можно отменить тут, в другом пуле уже сделали

2024-04-26 15:18 UTC, DitriXNew commented on IRP/src/Documents/ExpenseAccruals/ManagerModule.bsl
> +//  Parameters - Structure:
По правильному - да. Раз нет такой отдельной функции.

2024-04-28 20:10 UTC, mybracho commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("EmptyTransactionType", NStr("en = 'Transaction type not entered'", Lang));
Префиксы сделал. Регион "ErrorMessages". Там общие ошибки похожие есть. Более подходящего не нашел.

2024-04-29 19:25 UTC, merged