#IRP-423 Accounting service
IRPTeam/IRP pull request #2563
Opened 2024-08-05 09:09 UTC by andreyvorobyov2

2024-08-06 19:22 UTC, DitriXNew requested changes

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +//	Return AccountingServerReuse.GetMatchingLedgerTypes(LedgerType);
Удалить

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +				Errors.Add(StrTemplate("Debit is empty [%1] row-key[%2]", Row.Operation, TrimAll(Row.Key)));
вынеси в локализацию,  это всетаки не райзы

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +			_Date = BegOfDay(EndOfDay(_Date) + 1);
BegOfDay - лишний

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +			Return True;
Тут точно True?

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +	Return True;
Или тут? Не вижу когда функция False вернет

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +			If Not ValueIsFilled(NewRow.Company) And ValueIsFilled(NewRow.CompanyRef) Then
Тоже может в локализацю вынести? или это функции контроля для http?

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +	Type_Analytic = New TypeDescription(Metadata.ChartsOfCharacteristicTypes.AccountingExtraDimensionTypes.Type.Types());
Не используешь в коде

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +	Type_Analytic = New TypeDescription(Metadata.ChartsOfCharacteristicTypes.AccountingExtraDimensionTypes.Type.Types());
Не используешь

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +	While i <= 3 Do
Почему 3? Выведи плиз через именованую переменную, а то потом я буду гадать - что это и почему именно 3?

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +Procedure FillExdimensionsRow(Row, ExtDimension, AnalyticType)
опечатка ExtDimensions

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +	Row["Description_ru"    + AnalyticType + ExtDimension.Number] = ExtDimension.Value.Description_ru;
Есть функция в модуле локализации, которая возвращает все доступные локализации, может на нее завятся ,чтобы хардкодом не фигарить?

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +	BeginTransaction();
Rollback нету, это значит что если будет выше попытка, то транзакция не будет закрыта, а это приведет к печальным последствиям, что и наблюдались при интеграции с шиной. Лучше в Exception вставить райз, а перед ним сделать ролбэк

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +	If NewRefData.IsNewObject Then
А чего тут без транзакции?

2024-08-06 19:22 UTC, DitriXNew commented on IRP/src/CommonModules/DocExternalAccountingOperationServer/Module.bsl
> +//	LockDataModificationPrivileged.LockFormIfObjectIsLocked(Form, CurrentObject);
удалить

2024-08-08 11:05 UTC, andreyvorobyov2 commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +			Return True;
Точно. Это функция удаления. если объект был удален до того как был передан удалять его не нужно, его просто нет.

2024-08-08 11:07 UTC, andreyvorobyov2 commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +	Return True;
Никогда Fasle не вернет, возвращаемое значение сделано для унификации с функцией CreateExternalAccountingOperation

2024-08-08 11:13 UTC, andreyvorobyov2 commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +	BeginTransaction();
Там не нужна транзакция. осталась от отладки

2024-08-08 11:27 UTC, andreyvorobyov2 commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +	While i <= 3 Do
потому что 3 субконто

2024-08-12 11:53 UTC, merged