#IRP-436 Add Messaging subsystem
IRPTeam/IRP pull request #2578
Opened 2024-08-16 17:56 UTC by DementorAK

2024-08-23 17:15 UTC, DitriXNew requested changes

2024-08-23 17:15 UTC, DitriXNew commented on IRP/src/CommonModules/PictureViewerServer/Module.bsl
> +EndFunction
Это переделать надо, чтобы работало как гугл диск

2024-08-23 17:15 UTC, DitriXNew commented on IRP/src/Documents/OutgoingMessage/Commands/Send/CommandModule.bsl
> +EndProcedure
Вынести  в общий  модуль

2024-08-23 17:15 UTC, DitriXNew commented on IRP/src/InformationRegisters/MessagesQueueToSend/ManagerModule.bsl
> +			Log.Write("Send messages", ErrorDescription(), , , QuerySelection.Message);
Может в очередь писать так же последенюю возникшую ошибку?

2024-08-27 16:36 UTC, DementorAK commented on IRP/src/CommonModules/PictureViewerServer/Module.bsl
> +EndFunction
Не понял при чем тут гугл-диск - это универсальные функции для работы с файлами, которых тут не хватало.
Единственное, что стоило бы вынести отдельно - это работу с URL, но не такую упрощенную как у меня, а можно взять за основу этот проект https://github.com/vbondarevsky/Connector

2024-08-28 13:28 UTC, DitriXNew commented on IRP/src/CommonModules/PictureViewerServer/Module.bsl
> +EndFunction
[	ElsIf Not ExtensionCall_GetVolumeURLByIntegrationSettings(FullURL, IntegrationSettings, URI) Then](https://github.com/IRPTeam/IRP/blob/3eec15823bd4948be0fb8da1ac38c69bd605cf15/IRP/src/CommonModules/PictureViewerServer/Module.bsl#L306)

2024-08-29 07:22 UTC, DementorAK commented on IRP/src/CommonModules/PictureViewerServer/Module.bsl
> +EndFunction
@DitriXNew это ужасная функция, в которой тип возврата не документирован и зависит от значения параметров: 

- если LocalFileStorage, то возвращает путь к временному хранилищу 
- если внешний сайт, то возвращает URL и дальше все равно остается задача загрузки с учетом порта, прокси и TLS/SSL
- если расширение, то там может быть все что угодно (по умолчанию пустая строка)

2024-08-29 12:05 UTC, DitriXNew commented on IRP/src/CommonModules/PictureViewerServer/Module.bsl
> +EndFunction
У тебя есть отличный шанс это систематизировать.
И сделать функцию, которая будет возвращать структурированно по запросу - бинарник или URL, или разбить на две функции

2024-09-06 12:49 UTC, DitriXNew approved these changes

2024-09-06 12:49 UTC, DitriXNew commented on IRP/src/CommonModules/EmailMessagesServer/Module.bsl
> +// * BinaryData - BinaryData -
Ну тут или надо писать еще Undefined, или внизу пиши New BinaryData

2024-09-06 12:50 UTC, merged