#IRP-487 Autocreate company and agreement in partner
IRPTeam/IRP pull request #2612
Opened 2024-09-13 12:19 UTC by mybracho

2024-09-13 15:30 UTC, andreyvorobyov2 commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +Function GetDefaultMovementType()
Уже есть такая функция
`Catalogs.Companies.GetLegalCurrencies(Company);`

2024-09-13 15:32 UTC, andreyvorobyov2 commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +
уже есть такая фунция
`Catalogs.Companies.GetDefaultChoiceRef(Parameters)`

2024-09-13 15:37 UTC, andreyvorobyov2 commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +
уже есть такая функция
`Catalogs.Partners.GetCompaniesForPartner()`
и это не такой просто запрос как тут,
партнер может наследовать компанию по иерархии

2024-09-13 15:47 UTC, andreyvorobyov2 commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +
уже есть такая функция
Catalogs.Agreements.GetRefArrayByPartner()
или
Catalogs.Agreement.GetRefsArrayBySegment()

партнер может иметь соглашение если входит в сегмент с общим соглашением.

весь код связанный с данными уже есть в модулях менеджера, не надо писать его в модуле формы

2024-09-13 15:53 UTC, andreyvorobyov2 commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	PartnerTypeMustHaveCompany = False;
для этого есть функция
Catalogs.Partners.GetPartnerInfo()
расширяемая необходимыми полями в запросе

2024-09-16 08:16 UTC, mybracho commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +
Исправлено

2024-09-16 08:32 UTC, mybracho commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +
Исправлено

2024-09-16 08:37 UTC, mybracho commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	PartnerTypeMustHaveCompany = False;
Здесь не понял зачем исправлять. Функция Catalogs.Partners.GetPartnerInfo() нигде не используется к конфигурации если искать. Я воспользовался функцией общего модуля CommonFunctionsServer.GetAttributesFromRef, которая подходит к этой ситуации.

2024-09-16 08:40 UTC, mybracho commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +
Этой функцией воспользоваться не смог. Не возвращает она организацию. Пробовал вот так:

```
FilterParameters = New Structure;
AdditionalParameters = New Structure;
	
ArrayOfFilters = New Array();
ArrayOfFilters.Add(DocumentsClientServer.CreateFilterItem("DeletionMark", True, ComparisonType.NotEqual));
ArrayOfFilters.Add(DocumentsClientServer.CreateFilterItem("OurCompany", True, ComparisonType.Equal));
	
FilterParameters.Insert("CustomSearchFilter", DocumentsServer.SerializeArrayOfFilters(ArrayOfFilters));
FilterParameters.Insert("AdditionalParameters", DocumentsServer.SerializeArrayOfFilters(AdditionalParameters));
```

2024-09-16 09:36 UTC, andreyvorobyov2 commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +
если организацию партнера Legal name нужно то нужно указать в параметрах партнера

если нужна наша организация Company то ее из настроек пользователя брать надо.
этот запрос все равно либо упадет из за RLS либо вернет чужую первую попавшуюся организацию к которой пользователь не имеет никакого отношения

2024-09-16 09:38 UTC, andreyvorobyov2 commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	PartnerTypeMustHaveCompany = False;
во многих справочниках есть Get__имя справчника_Info() например GetAgreementInfo()
эти функции предназначены для получения данных справочника, если в запросе не хватает полей добавь их раздел SELECT

2024-09-16 09:41 UTC, andreyvorobyov2 commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +	LegalCurrenciesArray = Catalogs.Companies.GetLegalCurrencies(CompanyRef);
эта функция не может вернуть пустой массив, зечем весь этот ненужный код?
достаточно одной строчки

Return Catalogs.Companies.GetLegalCurrencies(CompanyRef)[0].CurrencyMovementType;

2024-09-16 10:05 UTC, mybracho commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +	LegalCurrenciesArray = Catalogs.Companies.GetLegalCurrencies(CompanyRef);
Исправлено

2024-09-24 18:52 UTC, DitriXNew requested changes

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +		|	Companies.OurCompany = TRUE";
прям явно Тру?

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +Function GetDefaultCompany()
Используй строгую типизацию по максимуму, укажи заголовки

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +	If QuestionResult = DialogReturnCode.Yes Then
Уменьшая где не надо когнитивную сложность - сделай что если не Да то ретурн.

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +	If ArrayOfAgreements.Count() Then
> 0

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +	If ArrayOfAgreements.Count() Then
И можно вообще в одну строку записать

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	If ValueIsFilled(FormOwnerRef) And
Вынеси условие в переменную и дай нормальное название ей

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	If QuestionResult = DialogReturnCode.Yes Then
можно через ретурн если не ДА

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +		Items.List.Refresh();
Лучше делать нотификацию об изменении, а не вот это вот все

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	CompanyObject.Type = PredefinedValue("Enum.CompanyLegalType.Company");
На сервере можно просто писать Enums...

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	AttributesStructure = CommonFunctionsServer.GetAttributesFromRef(PartnerRef, "Description_en, Description_ru, Description_tr, TaxID");
Там где то была функция которая возвращает локализационные строки

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	AttributesStructure = CommonFunctionsServer.GetAttributesFromRef(PartnerRef, "Description_en, Description_ru, Description_tr, TaxID");
И зачем ты вообще эту функцию дергаешь на сервере?

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	If CompaniesArray.Count() Then
> 0

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	If AttributesStructure.Customer Or
В переменную

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/CommonForms/EditUserSettings/Module.bsl
> +	NewRow_Catalogs.Insert("Synonym"      , R().Add_Settings_018);
А чего не синоним через метаданные?

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/CommonForms/EditUserSettings/Module.bsl
> +	NewSetting.Insert("PictureIndex"   , 12);
что такое 12?

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("QuestionToUser_033", NStr("en = 'Do you want to create new partner term?'", Lang));
Ты уже определись - или с большой буквы или с маленькой названия писал, а еще лучше - подставлять их на уровень выше через метаданные, посмотри функцию выше

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("Add_Settings_019", NStr("en = 'Do not help to create partner details'", Lang));
Это вопрос или утверждение? И я ни понимать что тут имеется ввиду?

2024-09-24 18:52 UTC, DitriXNew commented on IRP/src/CommonModules/UserSettingsServer/Module.bsl
> +		"Catalogs.AllCatalogs.AdditionalSettings.DontHelpToCreatePartnerDetails"));
Может тогда из метаданы и получишь? Зачем тут строка? А если переименуют справочник? И у тебя там лежит не сама метадатаобжет а строка.

2024-09-25 08:24 UTC, mybracho commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +	If ArrayOfAgreements.Count() Then
Тут не понял, что надо сделать. И в чем смысл сэкономить 3 строки.

2024-09-25 08:38 UTC, mybracho commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +		Items.List.Refresh();
Дима, зачем отказываться от ОбработкиОповещения?

2024-09-25 08:44 UTC, mybracho commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	AttributesStructure = CommonFunctionsServer.GetAttributesFromRef(PartnerRef, "Description_en, Description_ru, Description_tr, TaxID");
Функцию дергаю, что бы получить структуру с нужными мне полями. И далее использовать FillPropertiesValues

2024-09-25 08:51 UTC, mybracho commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	If AttributesStructure.Customer Or
Не понял, что в переменную.

2024-09-25 08:53 UTC, mybracho commented on IRP/src/CommonForms/EditUserSettings/Module.bsl
> +	NewRow_Catalogs.Insert("Synonym"      , R().Add_Settings_018);
Потому что в метаданных нет никакого объекта по сути. Это просто блок настроек в UserSettings

2024-09-25 08:56 UTC, mybracho commented on IRP/src/CommonForms/EditUserSettings/Module.bsl
> +	NewSetting.Insert("PictureIndex"   , 12);
12 это пиктограмма обработки. 1 справочник. Исправил на 1.

2024-09-25 09:00 UTC, mybracho commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("QuestionToUser_033", NStr("en = 'Do you want to create new partner term?'", Lang));
Определился. С маленькой. В справочнике Companies синоним Companies, а не Legal Name. А мне надо именно Legal Name в вопросе пользователю.

2024-09-25 09:02 UTC, mybracho commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("Add_Settings_019", NStr("en = 'Do not help to create partner details'", Lang));
Это не вопросы. Это дополнительные настройки пользователя. В этом блоке перечислены все настройки, которые попадают в блок AdditionalSettins

2024-09-25 09:04 UTC, mybracho commented on IRP/src/CommonModules/UserSettingsServer/Module.bsl
> +		"Catalogs.AllCatalogs.AdditionalSettings.DontHelpToCreatePartnerDetails"));
Такого мета объекта нет. Это просто строка настроек. Так сделаны все функции получения доп. настроек. Например AllDocuments_AdditionalSettings_DisableChangeAuthor

2024-09-25 11:55 UTC, DitriXNew commented on IRP/src/Catalogs/Agreements/Forms/ListForm/Module.bsl
> +	If ArrayOfAgreements.Count() Then
```bsl
ArrayOfAgreements = Catalogs.Agreements.GetRefsArrayByPartner(PartnerRef);
Return ArrayOfAgreements.Count() > 0
```

2024-09-25 11:56 UTC, DitriXNew commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	If AttributesStructure.Customer Or
Условие в переменную

2024-09-25 11:58 UTC, DitriXNew commented on IRP/src/CommonModules/Localization/Module.bsl
> +	Strings.Insert("Add_Settings_019", NStr("en = 'Do not help to create partner details'", Lang));
Я не понимпю из названия - что эта настройка делает. Дай более внятное навание, попроса чат гпт помочь тебе

2024-09-25 11:59 UTC, DitriXNew commented on IRP/src/Catalogs/Companies/Forms/ListForm/Module.bsl
> +	AttributesStructure = CommonFunctionsServer.GetAttributesFromRef(PartnerRef, "Description_en, Description_ru, Description_tr, TaxID");
Что мешает заполнять из ссылки? Передавая просто список полей которые надо заполнить третьим параметром?

2024-09-29 16:02 UTC, merged