#IRP-565 Check document existence before Undoposting
IRPTeam/IRP pull request #2689
Opened 2024-11-12 12:36 UTC by mybracho

2024-11-25 14:38 UTC, DitriXNew requested changes

2024-11-25 14:38 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +			If ValueIsFilled(DocObject.Ref) Then
ссылка может быть, ее установить ее через УстановитьНовуюСсылку. Лучше проверять по тому - заполнен ли реквизит DataVersion

2024-11-26 05:11 UTC, andreyvorobyov2 commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +			If ValueIsFilled(DocObject.Ref) Then
Луче бы проверил Deletion mark (через ElseIf) так же как QueryTable[0].Posted и просто записал документ с DeletionMark  = True
Это просто не обработанный вариант данных. зачем эти костыли-затычки нужны?

2024-11-28 14:56 UTC, DitriXNew requested changes

2024-11-28 14:56 UTC, DitriXNew commented on IRP/src/CommonModules/AccountingServer/Module.bsl
> +			If ValueIsFilled(DocObject.Ref) Then
ValueIsFilled(DocObject.Ref) - это не сработает, если ссылка установлена через SetRef, потому что значение будет заполнено, а документа  базе при этом не будет.
А ты попытаешься сделать анпостинг, ты или вообще то сравнение убери, или проверяй наличие объекта по версии данных, что гарантирует что объект есть в базе.

2024-11-29 14:50 UTC, merged